import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Snippet',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>

      </head>
      <body className={inter.className}>
        <header className=' h-20 w-full bg-indigo-50 flex flex-row
                          justify-center items-center'>
          <div>
            <h1 className='bold lg:text-3xl md:text-xl text-indigo-700'>Code Snippets Control System - CS&sup2;</h1>
          </div>
        </header>
        <main>
          <div className='container mx-auto lg:px-20 px-2'>
            {children}  
          </div>
        </main>
        <footer className='fixed bottom-0 h-32 w-full bg-indigo-500'>
          <div>
            
          </div>
        </footer>        
      </body>
    </html>
  )
}
